apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddog-ui
  namespace: reddog
  annotations:
    kubernetes.io/ingress.class: traefik
    #traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip  
spec:
  rules:
  - host: reddog28868.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: reddog-makeline
#   namespace: reddog
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
#     traefik.ingress.kubernetes.io/rewrite-target: /makeline # set path to result request
# spec:
#   rules:
#   - host: briarreddog.eastus.cloudapp.azure.com
#     http:
#       paths:
#       - path: /orders
#         pathType: Prefix
#         backend:
#           service:
#             name: make-line-service
#             port:
#               number: 8082  