apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
spec:
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 0h20m0s

