 apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
spec:
  releaseName: dapr
  chart:
    spec:
      chart: dapr
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3